"sudo apt-get install ncurses-term
set nocp
call pathogen#infect()

if has("syntax")
  syntax on
endif

let g:solarized_termcolors=256
set t_Co=16

set background=light
colorscheme solarized

filetype on
set nocompatible


map <silent> <m-p> :cp <cr>
map <silent> <m-n> :cn <cr>

"indentations
"nmap <D-[> <<
"nmap <D-]> >>
"vmap <D-[> <gv
"vmap <D-]> >gv


syntax enable

set cf
set clipboard+=unnamed
set history=256
set autowrite
set ruler
set nu
set nowrap
set timeoutlen=250
set ts=2
set bs=2
set shiftwidth=2
set nocp incsearch
set cinoptions=:0,p0,t0
set cinwords=if,else,while,do,for,switch,case
set formatoptions=tcqr

set cindent
set smartindent
set autoindent
set smarttab
set expandtab


set showmatch
set mat=5
"set list
set lcs=tab:\ \ ,eol:$,trail:~,extends:>,precedes:<
set novisualbell
set noerrorbells
set laststatus=2

set mousehide
set mouse=a


if has("autocmd")
  " File type detection. Indent based on filetype. Recommended.
  filetype plugin indent on
endif

    
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif